-- 게시판 최신글 정렬
SELECT TP.ID, TP.POST_TITLE, TU.USER_EMAIL
FROM TBL_POST TP
JOIN TBL_USER TU
ON TP.USER_ID = TU.ID
ORDER BY ID DESC;

--댓글을 단 사용자
SELECT TR.REPLY_CONTENT, TU.USER_EMAIL
FROM TBL_REPLY TR
JOIN TBL_USER TU
ON TR.USER_ID = TU.ID


/*
 * SQL의 실행 순서
 * 
 * FROM > JOIN > ON > WHERE > GROUP BY > HAVING > SELECT > ORDER BY
 * 
 * */

-- 주문자 정보 조회
-- 주문 날짜, 사용자의 이름
SELECT TBO.ORDER_START_DATE, TBB.BUYER_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID;

-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT TBU.*, TBP.PRODUCT_NAME
FROM (
	SELECT *
	FROM TBL_ORDER TBO
	WHERE PRODUCT_ID = (
		SELECT PRODUCT_ID
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
		HAVING COUNT(PRODUCT_ID) = (
			SELECT MAX(COUNT(PRODUCT_ID))
			FROM TBL_ORDER
			GROUP BY PRODUCT_ID
		)
	)
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;



-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
	SELECT PRODUCT_ID
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	HAVING COUNT(PRODUCT_ID) = (
		SELECT MAX(COUNT(PRODUCT_ID))
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
	)
);

-- 1) 상품 이름과 총 판매 매출 조회
SELECT 
	PRODUCT_NAME AS "상품명", 
	COUNT(PRODUCT_ID) * PRODUCT_PRICE AS "매출"
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE;

-- 2) 상품을 구매한 20 ~ 30대 구매자의 수 조회
SELECT COUNT(ID) || '건' AS "20~30대 주문 개수"
FROM TBL_ORDER
WHERE BUYER_ID IN (
	SELECT ID
	FROM TBL_BUYER
	WHERE BUYER_AGE >= 20 AND BUYER_AGE <= 39
);

-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회
SELECT TBU.BUYER_NAME
FROM (
	SELECT *
	FROM TBL_ORDER
	WHERE PRODUCT_ID = (
		SELECT ID
		FROM TBL_PRODUCT
		WHERE PRODUCT_BRAND ='뉴발란스'
	) 
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
WHERE TBU.BUYER_AGE = 20;

-- 4) 여성의 나이대별 평균 지출 금액 조회
SELECT 
	TBU.BUYER_AGE, 
	ROUND(AVG(TBP.PRODUCT_PRICE), 2)
FROM TBL_ORDER TBO 
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBU.BUYER_GENDER = '여'
GROUP BY TBU.BUYER_AGE
ORDER BY ROUND(AVG(TBP.PRODUCT_PRICE), 2) DESC;

-- 5) 쇼핑몰의 총 판매 액수 조회
SELECT SUM(TBP.PRODUCT_PRICE) AS "쇼핑몰 총 매출"
FROM TBL_ORDER TBO 
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;


-- 6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT TBU.BUYER_NAME, TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
WHERE PRODUCT_ID = (
	SELECT ID
	FROM (
		SELECT TBP.ID
		FROM TBL_ORDER TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		JOIN TBL_BUYER TBU
		ON TBO.BUYER_ID = TBU.ID
		GROUP BY TBP.ID, TBP.PRODUCT_BRAND, TBP.PRODUCT_PRICE
		ORDER BY SUM(TBP.PRODUCT_PRICE)
	)
	WHERE ROWNUM = 1
);

-- 7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
SELECT TBP.*, TBU.*
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
WHERE TBU.BUYER_ADDRESS LIKE '%경기도%';


-- 8) 30대 남성이 가장 많이 구매한 상품의 이름 조회
SELECT *
FROM (
	SELECT 
		PRODUCT_NAME AS "30대의 인기상품", 
		COUNT(PRODUCT_NAME) AS "구매 개수"
	FROM TBL_ORDER TBO
	JOIN TBL_BUYER TBU
	ON TBO.BUYER_ID = TBU.ID
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	WHERE TBU.BUYER_AGE BETWEEN 30 AND 39
	GROUP BY PRODUCT_NAME
	ORDER BY COUNT(PRODUCT_NAME) DESC
)
WHERE ROWNUM = 1;


-- 9) 가장 적게 판매된 상품의 이름
-- 10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
-- 11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
-- 12) 가장 인기가 없는 상품 조회












