CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	PRODUCT_COUNT NUMBER DEFAULT 1,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모니터', 200000, 1);

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK 
FROM TBL_PRODUCT

SELECT * FROM TBL_ORDER;

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, #{memberId}, #{productId}, #{productCount})

SELECT * FROM TBL_PRODUCT;


-- INSERT INTO TBL_MEMBER
-- VALUES(SEQ_MEMBER.NEXTVAL, 'test123@gmail.com', 'test123!@#', '홍길동');

SELECT * 
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_MEMBER TBM
ON TBO.MEMBER_ID = TBM.ID;

SELECT 
	TBO.ID, 
	TBO.MEMBER_ID,
	TBO.PRODUCT_ID,
	TBO.PRODUCT_COUNT,
	TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE AS "ORDER_TOTAL_PRICE",
	TBP.PRODUCT_NAME,
	TBP.PRODUCT_PRICE,
	TBP.PRODUCT_STOCK,
	TBM.MEMBER_EMAIL,
	TBM.MEMBER_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_MEMBER TBM
ON TBO.MEMBER_ID = TBM.ID
ORDER BY TBO.ID DESC;






